# Generated by Django 3.2.25 on 2025-09-01 09:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('police', 'Police Officer'), ('ngo', 'NGO Worker'), ('volunteer', 'Volunteer'), ('admin', 'Administrator')], default='citizen', help_text='User role determines access level and permissions', max_length=20)),
                ('organization', models.CharField(blank=True, help_text='Organization name (for police, NGO, volunteer roles)', max_length=200)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('phone_verified', models.BooleanField(default=False, help_text='Whether phone number has been verified')),
                ('id_document', models.FileField(blank=True, help_text='ID document for verification (police, NGO roles)', null=True, upload_to='id_documents/')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether user identity has been verified by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(editable=False, help_text='Unique case identifier', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='Full name of missing person', max_length=200)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age at time of disappearance', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('height', models.CharField(blank=True, help_text='Height (e.g., 5\'8", 175cm)', max_length=50)),
                ('weight', models.CharField(blank=True, help_text='Weight (e.g., 150 lbs, 68kg)', max_length=50)),
                ('hair_color', models.CharField(blank=True, max_length=50)),
                ('eye_color', models.CharField(blank=True, max_length=50)),
                ('distinguishing_features', models.TextField(blank=True, help_text='Scars, tattoos, birthmarks, etc.')),
                ('last_seen_location', models.CharField(help_text='Last known location', max_length=255)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('closed', 'Case Closed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about disappearance')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='missing_persons/')),
                ('reporter_relationship', models.CharField(blank=True, help_text='Relationship to missing person', max_length=100)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Missing Person',
                'verbose_name_plural': 'Missing Persons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(help_text='Detailed description of the sighting')),
                ('confidence_level', models.CharField(choices=[('high', "High - I'm certain it was them"), ('medium', 'Medium - I think it was them'), ('low', "Low - I'm not sure")], default='medium', max_length=20)),
                ('reporter_name', models.CharField(blank=True, max_length=200)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Under Investigation'), ('verified', 'Verified'), ('false_alarm', 'False Alarm')], default='new', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sightings', to='core.missingperson')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_sightings', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sightings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sighting',
                'verbose_name_plural': 'Sightings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('case_verification', 'Case Verification'), ('sighting_verification', 'Sighting Verification'), ('user_verification', 'User Verification')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_tasks', to='core.missingperson')),
                ('related_sighting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_tasks', to='core.sighting')),
            ],
            options={
                'verbose_name': 'Verification Task',
                'verbose_name_plural': 'Verification Tasks',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('case_update', 'Case Update'), ('sighting_report', 'New Sighting'), ('verification_complete', 'Verification Complete'), ('system', 'System Message')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.missingperson')),
                ('related_sighting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.sighting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='missingperson',
            name='additional_photos',
            field=models.ManyToManyField(blank=True, related_name='missing_person_photos', to='core.Photo'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_missing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FoundPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(editable=False, help_text='Unique found person case identifier', max_length=20, unique=True)),
                ('possible_name', models.CharField(blank=True, help_text='Name if known or provided', max_length=200)),
                ('estimated_age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('hair_color', models.CharField(blank=True, max_length=50)),
                ('eye_color', models.CharField(blank=True, max_length=50)),
                ('distinguishing_features', models.TextField(blank=True)),
                ('found_location', models.CharField(max_length=255)),
                ('found_date', models.DateField()),
                ('found_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unidentified', 'Unidentified'), ('identified', 'Identified'), ('reunited', 'Reunited with Family')], default='unidentified', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional details about found person')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='found_persons/')),
                ('found_by_organization', models.CharField(help_text='Hospital, NGO, or organization that found the person', max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identified_at', models.DateTimeField(blank=True, null=True)),
                ('additional_photos', models.ManyToManyField(blank=True, related_name='found_person_photos', to='core.Photo')),
            ],
            options={
                'verbose_name': 'Found Person',
                'verbose_name_plural': 'Found Persons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('verify', 'Verify'), ('reject', 'Reject'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
