# Generated by Django 3.2.25 on 2026-02-04 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251030_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundperson',
            name='face_embedding',
            field=models.TextField(blank=True, help_text='AI-generated face embedding vector stored as JSON text', null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='face_embedding_created_at',
            field=models.DateTimeField(blank=True, help_text='When the face embedding was last generated', null=True),
        ),
        migrations.AddField(
            model_name='foundperson',
            name='face_embedding_model',
            field=models.CharField(blank=True, help_text='Name of the AI model used to generate the face embedding', max_length=50),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='face_embedding',
            field=models.TextField(blank=True, help_text='AI-generated face embedding vector stored as JSON text', null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='face_embedding_created_at',
            field=models.DateTimeField(blank=True, help_text='When the face embedding was last generated', null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='face_embedding_model',
            field=models.CharField(blank=True, help_text='Name of the AI model used to generate the face embedding', max_length=50),
        ),
        migrations.CreateModel(
            name='PotentialMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(choices=[('missing', 'New Missing Report'), ('found', 'New Found Report')], help_text='Which type of report triggered this AI match suggestion', max_length=10)),
                ('distance', models.FloatField(help_text='Raw distance between face embeddings (lower = more similar)')),
                ('confidence', models.FloatField(help_text='Derived confidence score (0-100) from the AI model')),
                ('ai_model', models.CharField(blank=True, help_text='Name of AI model used during matching (e.g. DeepFace, face_recognition)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed Match'), ('rejected', 'Rejected / Not a Match')], default='pending', help_text='Human review status of this potential match', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When this match was reviewed by a human', null=True)),
                ('notes', models.TextField(blank=True, help_text='Reviewer notes and justification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_matches', to='core.foundperson')),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_matches', to='core.missingperson')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin/Officer who reviewed this match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Potential Match',
                'verbose_name_plural': 'Potential Matches',
                'ordering': ['-confidence', 'distance'],
                'unique_together': {('missing_person', 'found_person', 'triggered_by')},
            },
        ),
    ]
