# Generated by Django 3.2.25 on 2026-02-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260204_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of the person during the sighting (optional but recommended)', null=True, upload_to='sighting_photos/'),
        ),
    ]
