# Generated by Django 3.2.25 on 2026-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sighting_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='ai_match_score',
            field=models.FloatField(blank=True, help_text='AI confidence score (0.0 to 1.0) for face match with missing person', null=True),
        ),
    ]
