# Generated by Django 3.2.25 on 2026-02-24 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sighting_ai_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='estimated_age',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated age in years (1-120)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='sighting',
            name='estimated_height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated height in centimeters (50-300cm)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
